workflows:
  flutter-android-v2:
    name: Flutter Android v2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Clean
        script: flutter clean
      - name: Pub get
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk


