name: flutter_webview_fotmob
description: Flutter WebView App (Fotmob)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   # 5.0.0 → 6.0.0


